name: vector_desk_flutter
description: A Flutter client SDK for integrating VectorDesk AI chat.
version: 0.0.2
homepage: https://github.com/xunqun/vector_desk_flutter_client

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ">=3.7.0 <5.0.0"
  cloud_firestore: ">=5.5.0 <7.0.0"
  firebase_auth: ">=5.3.3 <7.0.0"
  intl: ">=0.19.0 <0.21.0"
  uuid: ^4.2.2
  image_picker: ^1.0.4
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
